# Generated by Django 5.2 on 2025-05-06 22:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Records with this field filled in are considered logically deleted.', null=True)),
                ('tax_id', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('birth_date', models.DateField()),
                ('info', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
